DROP DATABASE IF EXISTS `im2073_db`;
CREATE DATABASE `im2073_db`;

USE `im2073_db`;

CREATE TABLE `Users`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(60) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `hashPassword` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `phoneNumber` VARCHAR(20) NOT NULL,
    `isAdmin` TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE `Memes`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(60) NOT NULL,
    `descrip` TEXT,
    `image_link` VARCHAR(255) NOT NULL,
    `price` DECIMAL(10,2) NOT NULL
);

CREATE TABLE `Orders`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `customer_id` BIGINT UNSIGNED NOT NULL,
    `purchase_datetime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`customer_id`) REFERENCES `Users`(`id`)
);

CREATE TABLE `OrderItems`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `order_id` BIGINT UNSIGNED NOT NULL,
    `meme_id` BIGINT UNSIGNED NOT NULL,
    `meme_qty` BIGINT NOT NULL,
    FOREIGN KEY (`order_id`) REFERENCES `Orders`(`id`),
    FOREIGN KEY (`meme_id`) REFERENCES `Memes`(`id`)
);

